### ISSUE TITLE
[ Bug ] - AlgorithmSettings objects cannot be saved

### ISSUE THREAD

**Issue by NicolasGensollen** [aramis-lab/leaspy#56]
In GitLab by @little_nemo on Jan 8, 2022, 12:40

Under Leaspy 1.2.0 (installed via pip), `AlgorithmSettings` objects cannot be saved using the dedicated `.save` method anymore.

## Minimal Steps to Reproduce

In a Python console with Leaspy installed:

```python
>>> import leaspy
>>> algo_settings = leaspy.AlgorithmSettings("mcmc_saem")
>>> algo_settings.save("algo_settings.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nemo.fournier/projects/winter_school/disease-course-mapping-solutions/leaspy_tutorial/lib/python3.8/site-packages/leaspy/io/settings/algorithm_settings.py", line 253, in save
    algo_family = self.get_algo_family()
AttributeError: 'AlgorithmSettings' object has no attribute 'get_algo_family' 
```

## Expected Behaviour

The `AlgorithmSettings` object is saved without errors.

## Notes toward fixing the issue

After a quick search into the repo, it seems that the `get_algo_family` method called in the `save` method does not seem to be implemented. 

I can look further into this issue later during the coming week, unless someone as a clue as to whether I am missing something else here.

**Comment by NicolasGensollen** [comment]
In GitLab by @emaheux on Jan 8, 2022, 17:12

Fixed in !61, a patch version 1.2.1 should be released very soon since this is critical!
